postgresql: &postgresql
  adapter: postgresql
  username: postgres
  database: dashboard_<%= Rails.env %>

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] %>

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
