# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ed7e96e148bd80ae8503cf941d68478ba1cb4a17a025ca92cf7c752cf53d933f848791e0e4ca5990014a47e09144f0dc86d673a0c3503419b1e436c33d0b5dd

test:
  secret_key_base: fe76a6255e0c51d19ffe63ed0fc233e2e0c1755126e67282ac76ad64648577e5191679183375b15d8ef45c80b7b4f973077041255f6befe2f8d8ffb69da5d553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
